site_name: Tinfoil Documentation
nav:
    - Home: index.md
    - Network Install: network.md
    - USB Install: usb.md
    - Custom Index: custom_index.md
    - DRM: drm.md
    - MTP: mtp.md
theme:
    name: 'material'